vercel/terraform-provider-vercel

- vercel/data_source_project.go
- vercel/resource_project.go
- vercel/validator_framework.go
- vercel/validator_int64_items_in.go
- vercel/validator_map_items_min_count.go
- vercel/validator_string_length_between.go
- vercel/validator_string_one_of.go
- vercel/validator_string_regex.go
- vercel/validator_string_set_items_in.go
- Refactor framework validation to improve error cases
> Add project name validation

- client/project_create.go
- docs/resources/project.md
- vercel/resource_project.go
- vercel/resource_project_model.go
- vercel/resource_project_test.go
Fixes #13
Straightforward change to expose the API field.
> Support per-branch environment variables

- docs/index.md
- docs/resources/deployment.md
- docs/resources/project.md
- docs/resources/project_domain.md
- examples/provider/provider.tf
- examples/resources/vercel_project/import.sh
- examples/resources/vercel_project_domain/import.sh
- vercel/resource_deployment.go
- vercel/resource_project.go
- Move Deployment note into deployment resource
> Improve documentation around imports

- vercel/resource_dns_record.go
- vercel/resource_dns_record_test.go
> Support NS DNS Records

- client/project_get.go
> Parse Gitlab repo slugs from the response URL rather than using Project

- docs/data-sources/prebuilt_project.md
- go.mod
- go.sum
- vercel/data_source_alias.go
- vercel/data_source_file.go
- vercel/data_source_prebuilt_project.go
- vercel/data_source_project.go
- vercel/data_source_project_directory.go
- vercel/provider.go
- vercel/resource_alias.go
- vercel/resource_deployment.go
- vercel/resource_dns_record.go
- vercel/resource_project.go
- vercel/resource_project_domain.go
- vercel/resource_project_environment_variable.go
- [V12 release notes](https://github.com/hashicorp/terraform-plugin-framework/releases/tag/v0.12.0)
- [V13 release notes](https://github.com/hashicorp/terraform-plugin-framework/releases/tag/v0.13.0)
> Upgrade to terraform framework v13

- vercel/provider.go
> Fix nil pointer provider config issue

- client/project_get.go
- client/project_update_production_branch.go
- vercel/resource_project.go
- vercel/resource_project_model.go
- vercel/resource_project_test.go
> Add support for setting production_branch

- docs/data-sources/project.md
- vercel/data_source_project.go
> Add missing field to project data source

- client/project_domain_create.go
> use v10 REST API for project domain creation

- client/environment_variable_create.go
- client/project_get.go
- client/project_update.go
- docs/data-sources/project.md
- docs/resources/project.md
- vercel/data_source_alias.go
- vercel/data_source_file.go
- vercel/data_source_prebuilt_project.go
- vercel/data_source_project.go
- vercel/data_source_project_directory.go
- vercel/data_source_project_model.go
- vercel/data_source_project_test.go
- vercel/resource_alias.go
- vercel/resource_deployment.go
- vercel/resource_dns_record.go
- vercel/resource_project.go
- vercel/resource_project_domain.go
- vercel/resource_project_environment_variable.go
- vercel/resource_project_model.go
- vercel/resource_project_test.go
- vercel/resource_shared_environment_variable.go
> Add support for Vercel Authentication + Password Protection

- client/project_get.go
- client/project_protection_bypass_for_automation_update.go
- client/project_update.go
- docs/resources/project.md
- vercel/resource_project.go
- vercel/resource_project_domain_test.go
- vercel/resource_project_model.go
- vercel/resource_project_test.go
> Add support for protection bypass for automation

- client/environment_variable_update.go
- vercel/resource_project_environment_variable_model.go
- vercel/resource_project_environment_variable_test.go
> Fix issue updating sensitive project environment variables

- client/dns_record_create.go
- client/dns_record_get.go
- client/dns_record_update.go
- docs/resources/dns_record.md
- vercel/resource_dns_record.go
- vercel/resource_dns_record_model.go
- vercel/resource_dns_record_test.go
> Add support for comments on DNS records

- client/edge_config.go
- docs/resources/edge_config.md
- vercel/resource_alias.go
- vercel/resource_dns_record.go
- vercel/resource_edge_config.go
- vercel/resource_edge_config_test.go
- vercel/resource_edge_config_token.go
Fix some update-churn issues due to not using state for unknown IDs
> Add support for updating Edge Config

- client/project.go
- vercel/resource_project.go
Linking and Unlinking is now supported.
Closes #105
> Allow updating git_repository without recreating project

- docs/data-sources/project.md
- vercel/data_source_project.go
- vercel/data_source_project_test.go
> Add missing deploy_hooks to vercel_project data source

- docs/resources/project.md
- docs/resources/project_environment_variable.md
- docs/resources/shared_environment_variable.md
- vercel/resource_project.go
- vercel/resource_project_environment_variable.go
- vercel/resource_shared_environment_variable.go
It's a PEBKAC issue, but it's easy to miss when using Terraform as a part of a team, and the provider doesn't have special error handling for it.
https://github.com/vercel/terraform-provider-vercel/issues/183
> Add a doc message about sensitive environment variables policies

- vercel/resource_project_domain.go
- vercel/resource_project_domain_test.go
> Improve production domain validation

- client/dns_record.go
- client/environment_variable.go
- client/project.go
- client/shared_environment_variable.go
- docs/data-sources/project.md
- docs/data-sources/shared_environment_variable.md
- docs/resources/project.md
- docs/resources/project_environment_variable.md
- docs/resources/shared_environment_variable.md
- examples/resources/vercel_project_environment_variable/resource.tf
- examples/resources/vercel_shared_environment_variable/resource.tf
- vercel/data_source_project.go
- vercel/data_source_shared_environment_variable.go
- vercel/resource_project.go
- vercel/resource_project_environment_variable.go
- vercel/resource_project_environment_variable_test.go
- vercel/resource_project_test.go
- vercel/resource_shared_environment_variable.go
- vercel/resource_shared_environment_variable_test.go
> Add comment field to all env vars.

- client/project_deployment_retention.go
- vercel/data_source_project_deployment_retention.go
- vercel/data_source_project_deployment_retention_test.go
- vercel/resource_project_deployment_retention.go
- vercel/resource_project_deployment_retention_test.go
- vercel/resource_project_environment_variable.go
- vercel/resource_shared_environment_variable.go
> Allow 'unlimited' deployment retentions to be imported / updated to

- client/environment_variable.go
- client/error.go
- client/shared_environment_variable.go
This way you get the ID to import, rather than having no clue what the conflict is.
Closes #193
> Log out environment variable conflicts

- client/file.go
- vercel/data_source_prebuilt_project.go
> Change prebuilt data source to follow symlinks

- client/firewall_config.go
- docs/resources/firewall_config.md
- examples/resources/vercel_firewall_config/resource.tf
- vercel/provider_test.go
- vercel/resource_firewall_config.go
- vercel/resource_firewall_config_test.go
Add suport for values in firewall config rule conditions that are using operators that require a list
> [Firewall Config] Support values in conditions

- docs/resources/microfrontend_group.md
- docs/resources/microfrontend_group_membership.md
- examples/resources/vercel_microfrontend_group/resource.tf
- examples/resources/vercel_microfrontend_group_membership/resource.tf
The example was outdated, this PR corrects it
> Fix microfrontends documentation example

- vercel/data_source_prebuilt_project.go
- vercel/resource_deployment.go
There were three bugs with prebuilt deployments:
- The path_prefix was incorrectly trimmed before attempting to read
`.vercel/output/build.json`, which led to issues reading the file.
- The logic for walking the output directory did not account for the
`filePathMap` field in the `vc-config.json` files for functions, which
indicate which additional files should be included in the deployment.
- We resolved symlinks when walking the output directory, but to prevent
uploading too many of the same files over and over, we should just
upload these as a symlink directly. This is doubly relevant as there
are many symlinks in the `filePathMap`.
Ref #236
> Fix prebuilt deployment bugs

- client/alias.go
- vercel/resource_alias.go
- vercel/resource_alias_test.go
> Support updating of existing alias resources

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- This will allow the Linear sync to auto-assign to me.
- Provides more structured input.
Note, i'm disabling blank issue templates here, too.
> Add issue templates to the codebase

- client/project_deployment_retention.go
- vercel/data_source_project_deployment_retention.go
- vercel/resource_project_deployment_retention.go
> Fix inconsistent team_id in project_deployment_retention resource

- client/shared_environment_variable.go
- docs/data-sources/shared_environment_variable.md
- docs/resources/shared_environment_variable.md
- vercel/data_source_shared_environment_variable.go
- vercel/data_source_shared_environment_variable_test.go
- vercel/resource_shared_environment_variable.go
- vercel/resource_shared_environment_variable_test.go
> Support setting `apply_to_all_custom_environments` on `vercel_shared_environment_variable` resources

- vercel/resource_project.go
- vercel/resource_project_test.go
- vercel/resource_project_validators.go
Turns out this was just an issue with Unknown
> Re-enable Fluid + compute tier validator

- client/deployment.go
- docs/data-sources/deployment.md
- docs/resources/deployment.md
- vercel/data_source_deployment.go
- vercel/data_source_deployment_test.go
- vercel/resource_deployment.go
- vercel/resource_deployment_test.go
> Support meta field on deployment resource

- docs/data-sources/project_members.md
- docs/resources/project_members.md
- vercel/data_source_project_members.go
- vercel/resource_project_members.go
Looks like 'MEMBER" was accidentally listed instead of 'ADMIN'.
Closes #388
> Fix project_members roles

- docs/data-sources/project.md
- vercel/data_source_project.go
- vercel/resource_deployment.go
- vercel/resource_dns_record.go
- vercel/resource_microfrontend_group.go
- vercel/resource_project.go
In TF, there are 3 types for a value:
- Null - field is not specified
- Unknown - field is specified, but it's value isn't known at this point
in time.
- Known - field is specified, and it's value is known at this point in
time.
By using pointers to go structs, we supported Null and Known values, but
not Unknown. This caused issues when people calculate these fields in th
eir TF code.
> Fix typings internally to support Unknown values
