vercel/terraform-provider-vercel

- Taskfile.yml
- client/project_list.go
- sweep/main.go
- vercel/data_source_project_test.go
- Run via `task sweep`
- Will _automatically_ delete all projects beginning with `test-acc`
> Add sweeper for orphaned test resources

- docs/data-sources/project.md
- vercel/data_source_project.go
The Project struct is used by both the data_source
and the resource. However, git_branch for environment_variables
were only added to the resource.
> Fix environment variable bug following #20

- client/deployment_delete.go
- vercel/resource_deployment.go
- vercel/resource_deployment_model.go
For us it is important to delete deployments for terraform consistency
The deletion of the resource worked fine in our tests:
```
Terraform will perform the following actions:
- resource "vercel_deployment" "deployment" {
- domains    = [
- "avocado-git-dario-terraform-deployment-test.pollen.run",
] -> null
- git_source = {
- ref     = "dario-terraform-deployment-test" -> null
- repo_id = "449314886" -> null
- type    = "github" -> null
}
- id         = "dpl_9gBRCvWiw8ViYzAawNypNfNrLtK2" -> null
- production = false -> null
- project_id = "prj_xxxxxxxxxxxxxxxxt" -> null
- team_id    = "team_xxxxxxxxxxxxxxxxt" -> null
- url        = "avocado-ibsmgnaua.pollen.run" -> null
}
Plan: 0 to add, 0 to change, 1 to destroy.
──────────────────────────────────────────────────────────────────────────── …
```
> DeleteDeployment: Create a delete deployment method

- client/file_create.go
- vercel/resource_deployment.go
The `CreateFile` API call was omitting the `teamId` parameter, which is required for uploading files as a specific team. This works though, providing the API token has access to the personal account level too. If using a token scoped to a specific team, this would not work. 
Closes #39
> Fix permissions issue with uploading deployment files

- vercel/resource_dns_record.go
- vercel/resource_dns_record_model.go
Turns out using `string` or `int64` directly causes issues
when the value passed comes from somewhere else (is Unknown).
This causes the provider to panic internally, as the `Unknown` value
is unhandled.
Closes #48
> Use terraform types for all fields

- .github/workflows/test.yml
- vercel/data_source_file.go
- vercel/data_source_file_test.go
- vercel/data_source_project_directory.go
- vercel/data_source_project_directory_test.go
- vercel/resource_deployment.go
- vercel/resource_deployment_model.go
- vercel/resource_deployment_test.go
This change improves the terraform-provider code by supporting Windows in a more consistent/better manner. 
This is done by: 
- ensuring line-endings are disregarded when considering terraform state,
- ensuring path separators are standardised when uploading to Vercel (Closes #50) and when considering terraform state, and,
- adding windows-latest as an OS to run tests against as part of CI. 
Additional changes: 
- I've added a `concurrency` section to the `test` CI workflow. This will prevent outdated tests running if multiple pushes are done in quick succession, and will cancel old CI runs.
> Support windows filepaths / line endings

- vercel/data_source_file.go
- vercel/data_source_file_test.go
- vercel/data_source_project_directory.go
- vercel/data_source_project_directory_test.go
- vercel/resource_deployment.go
This was originally implemented to prevent spurious diffs when
swapping the same repository between windows and unix systems.
However, due to the lack of detection of binary files, such as png
images, this can cause some files to be corrupted.
Looking at the [file command behaviour](https://github.com/file/file/blob/f2a6e7cb7db9b5fd86100403df6b2f830c7f22ba/src/encoding.c#L151-L228)
it seems like detecting binary/non-binary files is extremely
non-trivial, and heuristic at best (meaning it could be wrong).
In order to prevent hard to detect/analyse issues, I think it's best to
just accept that some spurious changes can occur if swapping between
systems.
This relates to #50 and #53
Closes #61
> Remove windows line-ending conversions

- vercel/resource_project_environment_variable.go
This prevents it being displayed in plan/apply output. 
Ref #71
> Mark project_environment_variable value as sensitive

- vercel/resource_project.go
- vercel/resource_project_test.go
If importing a project that explicitly has environment variables, reading them as part of the import can be painful.
See #71 for details.
> Don't fetch env variables on project import

- go.mod
- go.sum
- vercel/data_source_alias.go
- vercel/data_source_file.go
- vercel/data_source_file_test.go
- vercel/data_source_prebuilt_project.go
- vercel/data_source_prebuilt_project_test.go
- vercel/data_source_project.go
- vercel/data_source_project_directory.go
- vercel/data_source_project_directory_test.go
- vercel/data_source_project_test.go
- vercel/provider.go
- vercel/resource_alias.go
- vercel/resource_deployment.go
- vercel/resource_dns_record.go
- vercel/resource_dns_record_test.go
- vercel/resource_project.go
- vercel/resource_project_domain.go
- vercel/resource_project_environment_variable.go
- vercel/validator_framework.go
- vercel/validator_int64_greater_than.go
- vercel/validator_int64_less_than.go
- vercel/validator_int64_one_of.go
- vercel/validator_map_items_min_count.go
- vercel/validator_serverless_function_region.go
- vercel/validator_string_length_between.go
- vercel/validator_string_one_of.go
- vercel/validator_string_regex.go
- vercel/validator_string_set_items_in.go
Release notes found here - https://github.com/hashicorp/terraform-plugin-framework/releases/tag/v0.17.0
This is mostly fundamental changes to how the schemas work across the provider, data sources and resources.
> Upgrade terraform-plugin-framework

- vercel/resource_deployment.go
- vercel/resource_deployment_test.go
Creating a vercel_deployment and passing a `null` environment variable results in a conversion error.
```
An unexpected error was encountered trying to build a value. This is always
an error in the provider. Please report the following to the provider
developer:
Received null value, however the target type cannot handle null values. Use
the corresponding `types` package type, a pointer type or a custom type that
handles null values.
Path: ["BAZ"]
Target Type: string
Suggested `types` Type: basetypes.StringValue
Suggested Pointer Type: *string
```
We need to handle the case where the field value is `null`, which is currently omitted.
Since the API only accepts string values for enviroment variables, the best solution is to simply omit sending `null` to the API altogether.
Closes #95
> Omit `null` environment variables in vercel_deployment

- README.md
I don't know much about terraform and I got confused when I clicked the link, took me a while to see the "documentation" tab on the right. Maybe this link should point directly to the docs ?
> fix the link to the docs

- vercel/resource_project.go
The environment variable diffing logic is more complex than it needs to be, and the current inner `continue` causes it to incorrectly detect changes, or no changes, based on target matching (it incorrectly skips to comparing the next `target`, not the next env var. 
It is much easier to just compare IDs, as we keep these in State, and TF detects changes as discarding the ID and a new one being computed.
> Fix environment variable diffing

- vercel/resource_project.go
- vercel/resource_project_test.go
At the moment, this should force recreation of the project, as we don't support updating or removing the linked repository.
See issue #105 for info on this.
However, there is a bug insofar as we don't explicitly flag this as requiring the project to be replaced. This creates an inconsistent plan.
Closes #133
> Fix issues with removing git_repository from a project

- vercel/data_source_alias.go
- vercel/data_source_project.go
- vercel/resource_alias.go
- vercel/resource_deployment.go
- vercel/resource_dns_record.go
- vercel/resource_project.go
- vercel/resource_project_domain.go
- vercel/resource_project_environment_variable.go
- vercel/resource_shared_environment_variable.go
Turns out it's computed for a good reason. If configuring team via the provider, then it should be a computed field (as the resource does not know the value until it is created). 
Avoid this by using `RequiresReplaceIfConfigured` instead. 
Closes #138. 
Closes #139.
> Fix team id differently

- vercel/resource_project.go
Vercel Authentication defaults to enabled for Projects as of 2nd November.
See [Changelog](https://vercel.com/changelog/deployment-protection-is-now-enabled-by-default-for-new-projects).
This has the effect that the terraform provider previously did not treat the authentication field as computed, so expected it to not be set.
Closes #142
> Use default value for vercel authentication field on project

- .github/workflows/test.yml
- README.md
- Taskfile.yml
- client/deployment_protection.go
- client/must_marshal.go
- client/project_get.go
- client/project_update.go
- docs/data-sources/alias.md
- docs/data-sources/file.md
- docs/data-sources/prebuilt_project.md
- docs/data-sources/project.md
- docs/data-sources/project_directory.md
- docs/index.md
- docs/resources/alias.md
- docs/resources/deployment.md
- docs/resources/dns_record.md
- docs/resources/project.md
- examples/provider/provider.tf
- vercel/data_source_project.go
- vercel/data_source_project_model.go
- vercel/data_source_project_test.go
- vercel/deployment_protection.go
- vercel/resource_project.go
- vercel/resource_project_model.go
- vercel/resource_project_test.go
- Add support for [Trusted IPs](https://vercel.com/docs/security/deployment-protection/methods-to-protect-deployments/trusted-ips)
- **[Breaking change]** Replace `protect_production` (boolean) with `deployment_type` (string) for [Password Protection](https://vercel.com/docs/security/deployment-protection/methods-to-protect-deployments/password-protection), [Vercel Authentication](https://vercel.com/docs/security/deployment-protection/methods-to-protect-deployments/vercel-authentication), and [Trusted IPs](https://vercel.com/docs/security/deployment-protection/methods-to-protect-deployments/trusted-ips)
- Make Vercel Authentication disable-able
- Update related tests & docs
Closes #144
> Update Deployment Protection support

- client/project_get.go
- client/project_update.go
- docs/data-sources/project.md
- docs/resources/project.md
- vercel/data_source_project.go
- vercel/data_source_project_model.go
- vercel/data_source_project_test.go
- vercel/resource_project.go
- vercel/resource_project_model.go
- vercel/resource_project_test.go
This is a feature [in the Vercel UI](https://vercel.com/docs/projects/environment-variables/system-environment-variables)
Add support to the TF provider.
Closes #158
> Add support for automatically exposing system env variables

- client/deploy_hooks.go
- client/deployment.go
- client/environment_variable.go
- client/project.go
- docs/resources/project.md
- vercel/data_source_project.go
- vercel/resource_deployment.go
- vercel/resource_project.go
- vercel/resource_project_domain.go
- vercel/resource_project_environment_variable.go
- vercel/resource_project_environment_variable_test.go
- vercel/resource_project_test.go
Deploy Hooks are available underneath the `git_repostiory` section of a
`vercel_project`.
These generate a URL that can be used to trigger new deployment of a
specific `ref`.
Existing on the `vercel_project` resource under `git_repository` is
the only place that seems to make sense, as linking/unlinking a
git repository causes all deploy hooks to require recreation, so
they cannot exist as a separate resource.
Closes #104
> Add support for Deploy Hooks

- vercel/data_source_project.go
Turns out git_comments in the response can be null, and this wasn't
handled for the data_source.
Can't test this effectively, as new projects _always_ have git_comments
set, which is why this was missed.
Closes #175
> Fix panic reading project data source

- client/client.go
- client/team.go
- sweep/main.go
- vercel/provider.go
- vercel/resource_project.go
- vercel/resource_project_environment_variable.go
- vercel/resource_project_environment_variable_test.go
- vercel/resource_project_test.go
- vercel/resource_shared_environment_variable.go
Turns out the API elides non-sensitive values into being sensitive if
the team has a sensitiveEnvironmentVariablePolicy set on it.
To prevent this from causing provider issues when the `sensitive` field
is explicitly set to `false`, warn at plan time that the resource being
created does not match the team policy.
Closes #183
> Validate sensitive environment variable config when creating env vars

- client/deployment_protection.go
- client/project.go
- docs/data-sources/project.md
- docs/resources/project.md
- vercel/data_source_project.go
- vercel/data_source_project_test.go
- vercel/deployment_protection.go
- vercel/resource_project.go
- vercel/resource_project_test.go
Add Terraform support for the new **OPTIONS Allowlist** feature
👉 [docs](https://vercel.com/docs/security/deployment-protection/methods-to-bypass-deployment-protection/options-allowlist)
👉 [changelog](https://vercel.com/changelog/options-allowlist)
> Add OPTIONS Allowlist support to vercel terraform provider

- vercel/resource_deployment.go
the `ref` description incorrectly says that `ref` is required if `ref` is not specified, when really I believe it means `files`.
> docs: update `ref` description in `resource_deployment` to fix reference to `files`

- docs/resources/firewall_config.md
- examples/resources/vercel_firewall_config/resource.tf
- vercel/resource_firewall_config.go
typo in docs uses camelcase instead of snakecase for `action_duration`
> [firewall-config] fix typo in docs

- client/project.go
- docs/data-sources/project.md
- docs/resources/project.md
- vercel/data_source_project.go
- vercel/data_source_project_test.go
- vercel/resource_project.go
- vercel/resource_project_test.go
Project's `oidcTokenConfig` now supports `issuerMode`. See https://vercel.com/docs/security/secure-backend-access/oidc#issuer-mode for more information on the property.
> Add `oidc_token_config.issuer_mode` property to projects

- vercel/resource_firewall_config.go
Exiting early after receiving an error and appending to diagnostics skips the followign line to append and early return after checking errors
> [firewall] return errors in diagnostics

- vercel/resource_deployment_test.go
Add a new test to the `create-deployment` so that we test when the `missing_files` error triggers and we have to process it.
It was a bit tricky as we need to avoid the cache: we need to create a random file with random contents.
> add missing_files test when creating deployments

- vercel/resource_firewall_config_test.go
An update to rule id generation invalidated the assumptions made in these id check tests for the firewall config resource
> [firewall] fix id check in resource tests

- client/team.go
- client/team_test.go
With certain permissions on the Vercel token, a get team request can return JSON that looks like:
```
{
...
"saml": {
...
"roles": {
"a": { "accessGroupId": "b" }
}
},
...
```
This fails to parse because we are expecting only JSON of the form:
```
{
...
"saml": {
...
"roles": {
"a": "ROLE"
}
},
...
```
This PR parses both forms and only exposes the role based form. Since we use PATCH for updating these states, it should be non-destructive when omitting this information coming from the API.
> Parse teams with saml configs containing access group objects as role values

- vercel/resource_project.go
- vercel/resource_project_environment_variables.go
- vercel/resource_project_environment_variables_test.go
Turns out it missed setting state at the end for the env vars that were
not being updated.
> Fix issue where updates to vercel_environment_variables was broke

- client/microfrontend_group_membership.go
The API has been updated to not accept `routeObservabilityToThisProject` for the default app
> Fix microfrontends routeObservabilityToThisProject

- vercel/resource_firewall_config.go
- vercel/resource_firewall_config_test.go
there is a check against the current tf state to convert go default values into terraform nil values
the check that passes the existing state is incorrect and will never pass the last condition in a condition group to the check, which casts the values to nil
> [firewall config resource] off by one error

- vercel/data_source_prebuilt_project.go
This means prebuilt projects referencing other files do not work
properly. This wasn't caught by tests because the files have previously
been uploaded to Vercel, so the hashes match existing files and the
paths are correct at deployment time.
Closes #236
> Fix - accidentally omitted path Prefix for filePathMap files

- vercel/resource_shared_environment_variable_project_link.go
- vercel/resource_team_member.go
This makes it appear that there are changes to be made to the resource,
as it's trying to do [] => null, but realistically they are the same.
> Fix issue where null values are incorrectly coerced to empty lists

- client/project.go
- vercel/data_source_project.go
- vercel/resource_project.go
- vercel/resource_project_test.go
- properly support null or unknown values for this field.
- remove false defaults of `null` for the fields.
- Fix validation allowing `0` or `901` as timeout values.
- Remove a lot of unnecessary code to suppress diffs.
- Allow setting resourceConfig on project creation.
> Fix usage of resource config on vercel_project resource.

- client/team.go
- docs/data-sources/team_config.md
- docs/resources/team_config.md
- vercel/data_source_team_config.go
- vercel/resource_team_config.go
- vercel/validator_saml_roles.go
At the moment, the `vercel_team_config` resource incorrectly implements Access Group support. If a team has SAML roles mapped access groups, the provider deletes the mappings.
**This is a breaking change**
steps for upgrading 👇 
1. Update schema for `vercel_team_config.saml`
1. If `vercel_team_config.saml.access_group_id` is specified: remove it
1. If `vercel_team_config.saml.roles` is specified: change the values of the object from strings to objects with the format `{ role = "<role e.g. VIEWER>" }` | `{ access_group_id = "<access_group_id>" }`
3. Refresh the terraform state with `terraform refresh` or `terraform apply`
```
// before
resource "vercel_team_config" "test_team" {
...
saml = {
enforced = <boolean>
access_group_id = "<access_group_id>"
roles = {
<directory_group_id> = "<role …
```
> [vercel_team_config] Fix saml dsync for access groups

- vercel/resource_team_config_test.go
Follow up to 
- https://github.com/vercel/terraform-provider-vercel/pull/298
I originally thought the tests would right themselves once in main, but it looks like the test will always produce a refresh now due to the multiple schema versions
Note that I tested the original change manually, and the refresh is only required once, after it's applied it's business as usual
> Fix `vercel_team_config` tests

- client/project.go
- docs/data-sources/project.md
- docs/resources/project.md
- vercel/data_source_project.go
- vercel/data_source_project_test.go
- vercel/resource_project.go
- vercel/resource_project_test.go
Support for these settings, but on a per-project basis. 
They can already be configured at the team basis in the `team_config` resource. 
Technically, the preview environments one already exists, in the `preview_comments` field on the `vercel_project` resource, but the name is kinda outdated, and mismatches the team settings. This should hopefully clarity that.
> Add support for Vercel Toolbar settings at project level

- vercel/resource_log_drain.go
- vercel/resource_log_drain_test.go
> Add firewall as a source on log_drain

- docs/resources/firewall_config.md
- examples/resources/vercel_firewall_config/resource.tf
- vercel/resource_firewall_config.go
- vercel/resource_firewall_config_test.go
Add terraform support for ai_bots managed ruleset.
API already supports this.
Tested locally with a project
> [firewall config resource] Add AI bots support

- vercel/resource_project_environment_variables.go
These seem to somehow mess up and cause env vars to be created with
values that are not expected or configured. No idea why.
> Bug: remove set plan modifiers on env variables resource

- docs/resources/team_config.md
- vercel/resource_team_config.go
This is causing refresh plans to be non-empty, as it continually thinks
the saml property is changing, even though it is not. The plan shows
zero changes (daft TF!).
Fix by removing the default, which conflicts when you have computed
state + UseStateForUnknown.
> Fix saml property on team config resource

- docs/resources/project_environment_variables.md
- vercel/resource_project_environment_variables.go
Seems this was accidentally comitted as commented out. Uncomment to mark them as sensitive. Note that this only affects the output of the Terraform CLI, and does not prevent the value from being stored in plaintext in the terraform state.
Closes #351
> Mark resource_environment_variables value as sensitive

- docs/resources/project_deployment_retention.md
- vercel/resource_project_deployment_retention.go
- vercel/resource_project_deployment_retention_test.go
This adds support for the 1 day and 1 week values for deployment retention policy. Not offered in the UI either but it does not break when changed to either of these values.
> Allow 1d and 1w for deployment retention policy

- client/deployment.go
- docs/data-sources/deployment.md
- docs/resources/deployment.md
- vercel/data_source_deployment.go
- vercel/data_source_deployment_test.go
- vercel/resource_deployment.go
- vercel/resource_deployment_test.go
This was missed from initial custom environment support. 
Closes #293
> Support custom environments in vercel_deployment data source + resource

- vercel/resource_shared_environment_variable.go
- vercel/resource_shared_environment_variable_test.go
This validator is incorrectly not skipping validation for unknown
values. This is a bit of a pain because calculated values are then
subject to validation which can be incorrect. Instead, for unknown
values rely on the API validating them.
> Fix shared-env validator

- client/environment_variable.go
- vercel/resource_project_environment_variables.go
- We don't log properly if every env var creation fails
- We were accidentally using encrypted values from the API response in
some instances when 2 env vars had the same name & target, but
different git branches.
> Fix a couple of bugs around env vars
